#! /usr/bin/env python

from genomon_expression.run import *
import argparse

parser = argparse.ArgumentParser(prog = "genomon_expression")

parser.add_argument("--version", action = "version", version = "genomon_expression-0.1.0")

parser.add_argument("bam_file", metavar = "sequence.bam", default = None, type = str,
                    help = "the path to the bam file")

parser.add_argument("output", metavar = "output.txt", default = None, type = str, 
                    help = "the path to the output")

parser.add_argument("exon_bed", metavar = "exon.bed", default = None, type = str,
                    help = "the path to the exon info file")

parser.add_argument("bedtools_path", metavar = "bedtools_path", default = None, type = str, 
                    help = "the path to bedtools")

parser.add_argument("-q", metavar = "mapping_qual_thres", default='20', type=int,
                    help = "threshold for mapping quality for calculating base counts")

args = parser.parse_args()

main(args)

